apiVersion: v2
appVersion: 0.3
description: A Helm chart for Kubernetes
name: radius
type: application
version: 0.1.0
maintainers:
  - name: xom4ek
    email: aleksei.lazarev@p2p.org
icon: https://avatars.githubusercontent.com/u/98524494?s=200&v=4
