node:
  # Configuration for the node container image
  image:
    repository: ghcr.io/layr-labs/eigenda/opr-node
    pullPolicy: Always
    tag: "0.9.0-rc.0"

  # Ports to expose from the node container
  internalRetrievalPort: 3204
  dispersalPort: 32005
  metricsPort: 9092
  nodeApiPort: 9091
  # Resource limits and requests for the node container
  resources: {}
  # Example resource limits and requests
  # limits:
  #   cpu: "4"
  #   memory: 4Gi
  # requests:
  #   cpu: "2"
  #   memory: 4Gi

  # Environment variables for the node container
  volumeMounts:
    - name: bls-key
      mountPath: /app/operator_keys/bls_key.json
      subPath: bls_key.json
      readOnly: true
    - name: ecdsa-key
      mountPath: /app/operator_keys/ecdsa_key.json
      subPath: ecdsa_key.json
      readOnly: true
    - name: eigenda
      mountPath: /app
  env:
    - name: NODE_ECDSA_KEY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: YOUR_SECRET_NAME
          key: ecdsa-private-key-password

    - name: NODE_BLS_KEY_PASSWORD
      valueFrom:
        secretKeyRef:
          name: YOUR_SECRET_NAME
          key: bls-private-key-password

  # Arguments to pass to the node container
  args: []
  # Example arguments for the node container
  # - --config=/app/config/worker-conf.toml

reverseProxy:
  nodeRetrievalPort: 32004

# Node selector for the pod
nodeSelector: {}

# Tolerations for the pod
tolerations: []

# Affinity rules for the pod
affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true

  # Annotations to add to the service account
  annotations: {}

  # The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# Annotations to add to the pod
podAnnotations: {}

# Security context for the pod
podSecurityContext: {}
# Example security context
# fsGroup: 2000

# Security context for the container
securityContext: {}
# Example security context
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

# Volumes for the pod
volumes:
  - name: bls-key
    secret:
      secretName: YOUR_SECRET_NAME
      items:
        - key: bls-key
          path: bls_key.json
  - name: ecdsa-key
    secret:
      secretName: YOUR_SECRET_NAME
      items:
        - key: ecdsa-key
          path: ecdsa_key.json
  - name: eigenda
    persistentVolumeClaim:
      claimName: eigenda

vmPodScrape:
  # Enable or disable VM Pod Scraping
  enabled: false

pvc:
  size: 100Gi
  storageClassName: "standard-rwo"
  labesl: {}
  annotations: {}

configs:
  # These are used for testing purpose
  NODE_TEST_PRIVATE_BLS: ""
  NODE_PRIVATE_KEY: ""

  # EigenDA specific configs
  NODE_EXPIRATION_POLL_INTERVAL: "180"
  NODE_CACHE_ENCODED_BLOBS: "true"
  NODE_NUM_WORKERS: "1"
  NODE_DISPERSAL_PORT: "32005"
  NODE_V2_DISPERSAL_PORT: "32006"

  # This flag defines a runtime mode. Acceptable inputs are v1-only, v2-only, v1-and-v2
  NODE_RUNTIME_MODE: "v1-and-v2"

  # This is a dummy value for now. This won't be used as we are explicitly asking for quorum while opting in/out
  # In future release, this will be removed
  NODE_QUORUM_ID_LIST: "0"

  NODE_VERBOSE: "true"
  NODE_RETRIEVAL_PORT: "32004"
  NODE_V2_RETRIEVAL_PORT: "32007"
  NODE_TIMEOUT: "20s"
  NODE_SRS_ORDER: "268435456"
  NODE_SRS_LOAD: "131072"

  # If you are using a reverse proxy in a shared network space, the reverse proxy should listen at $NODE_DISPERSAL_PORT
  # and forward the traffic to $NODE_INTERNAL_DISPERSAL_PORT, and similarly for retrieval. The DA node will register the
  # $NODE_DISPERSAL_PORT port on the chain and listen for the reverse proxy at $NODE_INTERNAL_DISPERSAL_PORT.
  NODE_INTERNAL_DISPERSAL_PORT: "32005"
  NODE_INTERNAL_RETRIEVAL_PORT: "32004"
  NODE_INTERNAL_V2_DISPERSAL_PORT: "32006"
  NODE_INTERNAL_V2_RETRIEVAL_PORT: "32007"


  # Reachability Check
  NODE_REACHABILITY_POLL_INTERVAL: "60"
  NODE_DATAAPI_URL: "https://dataapi-holesky.eigenda.xyz"

  # EigenDA mounted locations
  NODE_ECDSA_KEY_FILE: "/app/operator_keys/ecdsa_key.json"
  NODE_BLS_KEY_FILE: "/app/operator_keys/bls_key.json"
  NODE_G1_PATH: "/app/g1.point"
  NODE_G2_POWER_OF_2_PATH: "/app/g2.point.powerOf2"
  NODE_CACHE_PATH: "/app/cache"
  NODE_LOG_PATH: "/app/logs/opr.log"
  NODE_DB_PATH: "/data/operator/db"

  # Node logs configs
  NODE_LOG_LEVEL: "debug"
  NODE_LOG_FORMAT: "text"

  # Metrics specific configs
  NODE_ENABLE_METRICS: "true"
  NODE_METRICS_PORT: "9092"

  # Node API specific configs
  NODE_ENABLE_NODE_API: "true"
  NODE_API_PORT: "9091"

  # Holesky smart contracts
  NODE_EIGENDA_SERVICE_MANAGER: "0xD4A7E1Bd8015057293f0D0A557088c286942e84b"
  NODE_BLS_OPERATOR_STATE_RETRIVER: "0xB4baAfee917fb4449f5ec64804217bccE9f46C67"

  # Churner URL
  NODE_CHURNER_URL: "CHURNER-HOLESKY.EIGENDA.XYZ:443"

  # The name of the header used to get the client IP address
  # If set to empty string, the IP address will be taken from the connection.
  # The rightmost value of the header will be used.
  NODE_CLIENT_IP_HEADER: "x-real-ip"
  # How often to check the public IP address of the node. Set this to 0 to disable
  # automatic IP address updating (if you have a stable IP address)
  NODE_PUBLIC_IP_CHECK_INTERVAL: "10s"

  ###############################################################################
  ####### TODO: Operators please update below values for your node ##############
  ###############################################################################
  # TODO: IP of your node
  NODE_HOSTNAME: "YOUR_NODE_IP"

  # Nginx configuration for the reverse proxy
  REQUEST_LIMIT: "10r/s"
  NODE_HOST: "localhost"
  BURST_LIMIT: "50"

  # TODO: Operators need to point this to a working chain RPC
  NODE_CHAIN_RPC: "https://ethereum-holesky-rpc.publicnode.com"
  NODE_CHAIN_ID: "17000"

  #  # TODO: Operators need to update this to their own paths
  #  USER_HOME: "/app"
  #  EIGENLAYER_HOME: "/app/.eigenlayer"
  #  EIGENDA_HOME: "/app/.eigenlayer/eigenda/holesky"
  #
  #  NODE_LOG_PATH_HOST: "/app/logs"
  #  NODE_G1_PATH_HOST: "/app.eigenda-operator-setup/resources/g1.point"
  #  NODE_G2_PATH_HOST: "/app/eigenda-operator-setup/resources/g2.point.powerOf2"
  #  NODE_DB_PATH_HOST: "/app/db"
  #  NODE_CACHE_PATH_HOST: "/app/eigenda-operator-setup/resources/cache"
  #
  #  # TODO: Operators need to update this to their own keys
  #  NODE_ECDSA_KEY_FILE_HOST: "/app/.eigenlayer/operator_keys/opr.ecdsa.key.json"
  #  NODE_BLS_KEY_FILE_HOST: "/app/.eigenlayer/operator_keys/opr.bls.key.json"

  # TODO: The IP provider service used to obtain a node's public IP [seeip (default), ipify]
  NODE_PUBLIC_IP_PROVIDER: "seeip"

  #  # TODO: Operators need to add password to decrypt the above keys
  #  # If you have some special characters in password, make sure to use single quotes
  #  NODE_ECDSA_KEY_PASSWORD: ''
  #  NODE_BLS_KEY_PASSWORD: ''ODE_PUBLIC_IP_PROVIDER: "seeip"
